# Create new CSV file after how many hours:
cutFileInterval: 1

# Stop the main script after how many hours:
killScriptInterval: 4

modules:
  -
    name: imu
    type: IMUModule
    parameters:
      - "RTIMULib"
      - 500
  -
    name: geiger
    type: GeigerCounterModule
    parameters:
      - "/dev/ttyAMA0"
      - 9600